pipeline:
    name: pushusingapi
    identifier: api_artifact_push
    allowStageExecutions: false
    projectIdentifier: sample
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Build and Push jar
              identifier: Test_Build_and_Push
              type: CI
              spec:
                  cloneCodebase: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: deploy jar
                                identifier: deploy_jar
                                spec:
                                    connectorRef: docker
                                    image: maven
                                    command: |-
                                        for file in *;
                                        do
                                        if [ "$file" != *".sh" ]; then
                                        curl -u vinaykumar28044@gmail.com:Chinna@2804 -XPUT https://vinay28044.jfrog.io/artifactory/api-repo-libs-snapshot/$file -T $file
                                        fi
                                        done
                                    privileged: false
                                when:
                                    stageStatus: Success
                                failureStrategies: []
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: newgcp
                          namespace: harness-delegate-ng
              variables:
                  - name: myStageVar
                    type: String
                    value: stageVarValue
    properties:
        ci:
            codebase:
                connectorRef: gitconnector
                build: <+input>
    variables:
        - name: pipelineVar
          type: String
          value: pipelineVarValue
