pipeline:
    name: CI
    identifier: CI
    allowStageExecutions: false
    projectIdentifier: sample
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Build Test and Push
              identifier: Test_Build_and_Push
              type: CI
              spec:
                  cloneCodebase: false
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Maven Build
                                identifier: Go_Build
                                spec:
                                    connectorRef: docker
                                    image: maven
                                    command: mvn clean install
                                    privileged: false
                                when:
                                    stageStatus: Success
                                failureStrategies: []
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: Build and push image to DockerHub
                                identifier: Build_and_push_image_to_DockerHub
                                spec:
                                    connectorRef: docker
                                    repo: bluebbb/godemo
                                    tags:
                                        - latest
                                    optimize: true
                                failureStrategies: []
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: gcp
                          namespace: default
              variables:
                  - name: myStageVar
                    type: String
                    value: stageVarValue
    properties:
        ci:
            codebase:
                connectorRef: gitconnector
                build: <+input>
    variables:
        - name: pipelineVar
          type: String
          value: pipelineVarValue
