pipeline:
    name: custom-ci
    identifier: customci
    allowStageExecutions: false
    projectIdentifier: sample
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Build and Push Image
              identifier: Test_Build_and_Push
              type: CI
              spec:
                  cloneCodebase: true
                  execution:
                      steps:
                          - step:
                                type: ArtifactoryUpload
                                name: to jfrog
                                identifier: to_jfrog
                                spec:
                                    connectorRef: jfrog
                                    target: https://vinay28044.jfrog.io/artifactory/default-maven-virtual/
                                    sourcePath: art
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: newgcp
                          namespace: harness-delegate-ng
              variables:
                  - name: myStageVar
                    type: String
                    value: stageVarValue
    properties:
        ci:
            codebase:
                connectorRef: gitconnector
                build: <+input>
    variables:
        - name: pipelineVar
          type: String
          value: pipelineVarValue
