apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}
data:
  config.properties: |-
{{.Values.env.config.properties | b64dec | indent 4}}
  Key={{.Values.Key}}
  abc.properties: |-
{{.Values.env.config.properties | b64dec | indent 4}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}
stringData:
{{.Values.env.secrets | toYaml | indent 4}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.label}}
  template:
    metadata:
      labels:
        app: {{.Values.label}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        ports:
        - containerPort: {{.Values.serviceTargetPort}}
        envFrom:
        {{- if .Values.env.secrets}}
        - secretRef:
            name: {{.Values.name}}
        {{- end}}
        volumeMounts:
        - name: {{.Values.name}}
          mountPath: {{.Values.mountpathname}}
      volumes:
        - name: {{.Values.name}}
          configMap:
            name: {{.Values.name}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.label}}
spec:
  type: {{.Values.serviceType}}
  selector:
    app: {{.Values.label}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
