name: dev
replicas: 1

image: <+artifact.image>

createNamespace: true
namespace: <+infra.namespace>

serviceType: LoadBalancer

servicePort: 80
serviceTargetPort: 8080
mountpathname: test
devconfigpwd: <+pipeline.variables.devconfigpwd>
devabcpwd: <+pipeline.variables.devabcpwd>
env:
  config:
    properties: <+secrets.getValue("devconfig")>
    properties1: <+secrets.getValue("devabc")>
