name: dev-deploy
replicas: 1

image: <+artifact.image>

createNamespace: true
namespace: <+infra.namespace>

serviceType: LoadBalancer

servicePort: 80
serviceTargetPort: 8080
mountpathname: dev-deploy
env:
  config:
    config.properties: config.properties
  secrets:
    username: ${serviceVariable.username}
    pwd: ${serviceVariable.pwd}
