name: dev
replicas: 1

image: <+artifact.image>

createNamespace: true
namespace: <+infra.namespace>

serviceType: LoadBalancer
dfc: hardcoded

servicePort: 80
serviceTargetPort: 8080
mountpathname: test
Key: <+pipeline.variables.ENVIRONMENT>
env:
  config:
    properties: <+secrets.getValue("config")>
