apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      name: web-app-pod1
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app-container
        image: <+artifact.image>
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webappservice
  labels:
    app: web-app
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - port:80
      targetPort: 8080
