# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/cache@v2
      id: cache-packages 
      with:
        path: /IBMJDK
        key: ${{ runner.os }}-/IBMJDK
        restore-keys: |
          ${{ runner.os }}-/IBMJDK
        
    - name: Download Java
      if: steps.cache-packages.outputs.cache-hit != 'true'
      run: |
          wget -O javaSDK.bin http://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/7.0.10.85/linux/x86_64/ibm-java-sdk-7.0-10.85-x86_64-archive.bin
          chmod a+x javaSDK.bin
          
    - name: Create Java Config file
      if: steps.cache-packages.outputs.cache-hit != 'true'
      run: |
           echo 'LICENSE_ACCEPTED=TRUE' > installer.properties
           echo 'USER_INSTALL_DIR=/IBMJDK' >> installer.properties  
     
    - name: Install Java
      if: steps.cache-packages.outputs.cache-hit != 'true'
      run: ./javaSDK.bin  -i silent 
    #- name: Download Maven
      #run: |
            #curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
            #sudo unzip -d /usr/share maven.zip
            #sudo rm maven.zip
            #sudo ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
    - name: Build JAR
      run: |
           export JAVA_HOME="/IBMJDK/jre"
           mvn -B package -f pom.xml
           cd target 
           ls -a
           

          
      
           
       
