name: Build and deploy JAR app to Azure Web App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
      - name: Download code from Git
        uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Check the version of Java and Maven
        run: |
          java -version
          mvn -version
          echo "mallik"

      - name: Creating .jar file
        run: mvn install

      - name: to find .jar file and upload to the Github repository
        run: |
          cd target
          ls -l
          
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: 1stProjectArtifact
      #     path: target/jb-hello-world-maven-0.2.0.jar

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: Ap03272024
          slot-name: production  # Change this if you use deployment slots
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_66a1b854dca24f6d9512af9330f507c3 }}
          package: ${{ github.workspace }}/target/*.jar
            
