# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Download Java
      run: |
          wget -O javaSDK.zip https://ak-delivery04-mul.dhe.ibm.com/sdfdl/v2/sar/CM/WS/09www/0/Xa.2/Xb.jusyLTSp44S045SveZXfHhwc5hH9B-xD93CK1e2345Sv1LUGHKzpetInouc/Xc.CM/WS/09www/0/ibm-java-sdk-8.0-6.35-linux-x64-installmgr.zip/Xd./Xf.LPR.D1vk/Xg.11378696/Xi.habanero/XY.habanero/XZ.IYuE1zFpfqMU71kyeREWxa0QqYakLJqQ/ibm-java-sdk-8.0-6.35-linux-x64-installmgr.zip
          unzip javaSDK.zip
          chmod a+x javaSDK.bin
          echo 'LICENSE_ACCEPTED=TRUE' > installer.properties
          echo 'USER_INSTALL_DIR=${{ runner.temp }}/IBMJDK' >> installer.properties
    - name: Install Java
      run: ./javaSDK.bin  -i silent 
    #- name: Download Maven
      #run: |
            #curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
            #sudo unzip -d /usr/share maven.zip
            #sudo rm maven.zip
            #sudo ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
    - name: Build JAR
      #working-directory: ./CapacityCollector
      run: |
           export JAVA_HOME="${{ runner.temp }}/IBMJDK/jre"
           mvn -B package -f pom.xml
           cd target 
           ls -a
