# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
 
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        jdkFile: http://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/8.0.6.35/linux/i386/ibm-java-jre-8.0-6.35-i386-archive.bin?_ga=2.252663370.277456827.1629139829-893882425.1628613710
    - run: java --version

    - name: Build with Maven
      run: java -v

